#ifndef __UNIFINGER_VERSION_H__
#define __UNIFINGER_VERSION_H__

#define SFM_SDK_VERSION_INFO
#define SFM_SDK_VERSION_MAJOR 3
#define SFM_SDK_VERSION_MINOR 1
#define SFM_SDK_VERSION_REVISION 2

#endif
