/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_supremainc_sfm_sdk_SFM_SDK_ANDROID */

#ifndef _Included_com_supremainc_sfm_sdk_SFM_SDK_ANDROID
#define _Included_com_supremainc_sfm_sdk_SFM_SDK_ANDROID
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    _SetupSerialCallback
 * Signature: (Lcom/supremainc/sfm_sdk/callback_interface/SFM_SDK_ANDROID_CALLBACK_INTERFACE/SetupSerialCallback;)V
 */
JNIEXPORT void JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID__1SetupSerialCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    _ReadSerialCallback
 * Signature: (Lcom/supremainc/sfm_sdk/callback_interface/SFM_SDK_ANDROID_CALLBACK_INTERFACE/ReadSerialCallback;)V
 */
JNIEXPORT void JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID__1ReadSerialCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    _WriteSerialCallback
 * Signature: (Lcom/supremainc/sfm_sdk/callback_interface/SFM_SDK_ANDROID_CALLBACK_INTERFACE/WriteSerialCallback;)V
 */
JNIEXPORT void JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID__1WriteSerialCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    _SendPacketCallback
 * Signature: (Lcom/supremainc/sfm_sdk/callback_interface/SFM_SDK_ANDROID_CALLBACK_INTERFACE/SendPacketCallback;)V
 */
JNIEXPORT void JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID__1SendPacketCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    _ReceivePacketCallback
 * Signature: (Lcom/supremainc/sfm_sdk/callback_interface/SFM_SDK_ANDROID_CALLBACK_INTERFACE/ReceivePacketCallback;)V
 */
JNIEXPORT void JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID__1ReceivePacketCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    _SendDataPacketCallback
 * Signature: (Lcom/supremainc/sfm_sdk/callback_interface/SFM_SDK_ANDROID_CALLBACK_INTERFACE/SendDataPacketCallback;)V
 */
JNIEXPORT void JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID__1SendDataPacketCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    _ReceiveDataPacketCallback
 * Signature: (Lcom/supremainc/sfm_sdk/callback_interface/SFM_SDK_ANDROID_CALLBACK_INTERFACE/ReceiveDataPacketCallback;)V
 */
JNIEXPORT void JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID__1ReceiveDataPacketCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    _SendRawDataCallback
 * Signature: (Lcom/supremainc/sfm_sdk/callback_interface/SFM_SDK_ANDROID_CALLBACK_INTERFACE/SendRawDataCallback;)V
 */
JNIEXPORT void JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID__1SendRawDataCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    _ReceiveRawDataCallback
 * Signature: (Lcom/supremainc/sfm_sdk/callback_interface/SFM_SDK_ANDROID_CALLBACK_INTERFACE/ReceiveRawDataCallback;)V
 */
JNIEXPORT void JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID__1ReceiveRawDataCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    _UserInfoCallback
 * Signature: (Lcom/supremainc/sfm_sdk/callback_interface/SFM_SDK_ANDROID_CALLBACK_INTERFACE/UserInfoCallback;)V
 */
JNIEXPORT void JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID__1UserInfoCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    _ScanCallback
 * Signature: (Lcom/supremainc/sfm_sdk/callback_interface/SFM_SDK_ANDROID_CALLBACK_INTERFACE/ScanCallback;)V
 */
JNIEXPORT void JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID__1ScanCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    _IdentifyCallback
 * Signature: (Lcom/supremainc/sfm_sdk/callback_interface/SFM_SDK_ANDROID_CALLBACK_INTERFACE/IdentifyCallback;)V
 */
JNIEXPORT void JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID__1IdentifyCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    _VerifyCallback
 * Signature: (Lcom/supremainc/sfm_sdk/callback_interface/SFM_SDK_ANDROID_CALLBACK_INTERFACE/VerifyCallback;)V
 */
JNIEXPORT void JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID__1VerifyCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    _EnrollCallback
 * Signature: (Lcom/supremainc/sfm_sdk/callback_interface/SFM_SDK_ANDROID_CALLBACK_INTERFACE/EnrollCallback;)V
 */
JNIEXPORT void JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID__1EnrollCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    _DeleteCallback
 * Signature: (Lcom/supremainc/sfm_sdk/callback_interface/SFM_SDK_ANDROID_CALLBACK_INTERFACE/DeleteCallback;)V
 */
JNIEXPORT void JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID__1DeleteCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_GetSDKVersion
 * Signature: ([I[I[I)V
 */
JNIEXPORT void JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1GetSDKVersion
  (JNIEnv *, jobject, jintArray, jintArray, jintArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_InitCommPort
 * Signature: (Ljava/lang/String;IZ)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1InitCommPort
  (JNIEnv *, jobject, jstring, jint, jboolean);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_CloseCommPort
 * Signature: ()Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1CloseCommPort
  (JNIEnv *, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_Reconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1Reconnect
  (JNIEnv *, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_SetBaudrate
 * Signature: (I)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1SetBaudrate
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_SetAsciiMode
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1SetAsciiMode
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_SendPacket
 * Signature: (BIIBI)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1SendPacket
  (JNIEnv *, jobject, jbyte, jint, jint, jbyte, jint);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_SendNetworkPacket
 * Signature: (BSIIBI)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1SendNetworkPacket
  (JNIEnv *, jobject, jbyte, jshort, jint, jint, jbyte, jint);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_ReceivePakcet
 * Signature: ([BI)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1ReceivePakcet
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_ReceiveNetworkPakcet
 * Signature: ([BI)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1ReceiveNetworkPakcet
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_SendRawData
 * Signature: ([BII)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1SendRawData
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_ReceiveRawData
 * Signature: ([BIIZ)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1ReceiveRawData
  (JNIEnv *, jobject, jbyteArray, jint, jint, jboolean);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_SendDataPacket
 * Signature: (B[BII)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1SendDataPacket
  (JNIEnv *, jobject, jbyte, jbyteArray, jint, jint);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_ReceiveDataPacket
 * Signature: (B[BI)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1ReceiveDataPacket
  (JNIEnv *, jobject, jbyte, jbyteArray, jint);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_SetDefaultPacketSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1SetDefaultPacketSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_GetDefaultPacketSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1GetDefaultPacketSize
  (JNIEnv *, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_SetProtocol
 * Signature: (Lcom/supremainc/sfm_sdk/enumeration/UF_PROTOCOL;I)V
 */
JNIEXPORT void JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1SetProtocol
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_GetProtocol
 * Signature: ()Lcom/supremainc/sfm_sdk/enumeration/UF_PROTOCOL;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1GetProtocol
  (JNIEnv *, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_GetModuleID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1GetModuleID
  (JNIEnv *, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_SetGenericCommandTimeout
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1SetGenericCommandTimeout
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_SetInputCommandTimeout
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1SetInputCommandTimeout
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_GetGenericCommandTimeout
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1GetGenericCommandTimeout
  (JNIEnv *, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_GetInputCommandTimeout
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1GetInputCommandTimeout
  (JNIEnv *, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_SetNetWorkDelay
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1SetNetWorkDelay
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_GetNetworkDelay
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1GetNetworkDelay
  (JNIEnv *, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_Command
 * Signature: (B[I[I[B)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1Command
  (JNIEnv *, jobject, jbyte, jintArray, jintArray, jbyteArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_CommandEx
 * Signature: (B[I[I[BLcom/supremainc/sfm_sdk/callback_interface/SFM_SDK_ANDROID_CALLBACK_INTERFACE/MsgCallback;)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1CommandEx
  (JNIEnv *, jobject, jbyte, jintArray, jintArray, jbyteArray, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_CommandSendData
 * Signature: (B[I[I[B[BI)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1CommandSendData
  (JNIEnv *, jobject, jbyte, jintArray, jintArray, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_CommandSendDataEx
 * Signature: (B[I[I[B[BILcom/supremainc/sfm_sdk/callback_interface/SFM_SDK_ANDROID_CALLBACK_INTERFACE/MsgCallback;Z)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1CommandSendDataEx
  (JNIEnv *, jobject, jbyte, jintArray, jintArray, jbyteArray, jbyteArray, jint, jobject, jboolean);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_Cancel
 * Signature: (Z)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1Cancel
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_GetModuleInfo
 * Signature: (Lcom/supremainc/sfm_sdk/structure/UFModuleInfo;)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1GetModuleInfo
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_GetModuleString
 * Signature: (Lcom/supremainc/sfm_sdk/enumeration/UF_MODULE_TYPE;Lcom/supremainc/sfm_sdk/enumeration/UF_MODULE_VERSION;Lcom/supremainc/sfm_sdk/enumeration/UF_MODULE_SENSOR;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1GetModuleString
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_SearchModule
 * Signature: (Ljava/lang/String;[I[Z[Lcom/supremainc/sfm_sdk/enumeration/UF_PROTOCOL;[ILcom/supremainc/sfm_sdk/callback_interface/SFM_SDK_ANDROID_CALLBACK_INTERFACE/SearchModuleCallback;)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1SearchModule
  (JNIEnv *, jobject, jstring, jintArray, jbooleanArray, jobjectArray, jintArray, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_SearchModuleID
 * Signature: ([I)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1SearchModuleID
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_SearchModuleIDEx
 * Signature: ([SI[S[I)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1SearchModuleIDEx
  (JNIEnv *, jobject, jshortArray, jint, jshortArray, jintArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_CalibrateSensor
 * Signature: ()Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1CalibrateSensor
  (JNIEnv *, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_Reset
 * Signature: ()Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1Reset
  (JNIEnv *, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_Lock
 * Signature: ()Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1Lock
  (JNIEnv *, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_Unlock
 * Signature: ([B)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1Unlock
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_ChangePassword
 * Signature: ([B[B)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1ChangePassword
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_PowerOff
 * Signature: ()Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1PowerOff
  (JNIEnv *, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_InitSysParameter
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1InitSysParameter
  (JNIEnv *, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_GetSysParameter
 * Signature: (Lcom/supremainc/sfm_sdk/enumeration/UF_SYS_PARAM;[I)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1GetSysParameter
  (JNIEnv *, jobject, jobject, jintArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_SetSysParameter
 * Signature: (Lcom/supremainc/sfm_sdk/enumeration/UF_SYS_PARAM;I)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1SetSysParameter
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_GetMultiSysParameter
 * Signature: (I[Lcom/supremainc/sfm_sdk/enumeration/UF_SYS_PARAM;[I)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1GetMultiSysParameter
  (JNIEnv *, jobject, jint, jobjectArray, jintArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_SetMultiSysParameter
 * Signature: (I[Lcom/supremainc/sfm_sdk/enumeration/UF_SYS_PARAM;[I)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1SetMultiSysParameter
  (JNIEnv *, jobject, jint, jobjectArray, jintArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_Save
 * Signature: ()Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1Save
  (JNIEnv *, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_GetNumOfTemplate
 * Signature: ([I)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1GetNumOfTemplate
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_GetMaxNumOfTemplate
 * Signature: ([I)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1GetMaxNumOfTemplate
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_GetAllUserInfo
 * Signature: ([Lcom/supremainc/sfm_sdk/structure/UFUserInfo;[I[I)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1GetAllUserInfo
  (JNIEnv *, jobject, jobjectArray, jintArray, jintArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_GetAllUserInfoEx
 * Signature: ([Lcom/supremainc/sfm_sdk/structure/UFUserInfoEx;[I[I)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1GetAllUserInfoEx
  (JNIEnv *, jobject, jobjectArray, jintArray, jintArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_SetAdminLevel
 * Signature: (ILcom/supremainc/sfm_sdk/enumeration/UF_ADMIN_LEVEL;)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1SetAdminLevel
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_GetAdminLevel
 * Signature: (I[Lcom/supremainc/sfm_sdk/enumeration/UF_ADMIN_LEVEL;)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1GetAdminLevel
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_SetSecurityLevel
 * Signature: (ILcom/supremainc/sfm_sdk/enumeration/UF_USER_SECURITY_LEVEL;)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1SetSecurityLevel
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_GetSecurityLevel
 * Signature: (I[Lcom/supremainc/sfm_sdk/enumeration/UF_USER_SECURITY_LEVEL;)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1GetSecurityLevel
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_ClearAllAdminLevel
 * Signature: ()Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1ClearAllAdminLevel
  (JNIEnv *, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_SaveDB
 * Signature: (Ljava/lang/String;)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1SaveDB
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_LoadDB
 * Signature: (Ljava/lang/String;)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1LoadDB
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_CheckTemplate
 * Signature: (I[I)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1CheckTemplate
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_ReadTemplate
 * Signature: (I[I[B)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1ReadTemplate
  (JNIEnv *, jobject, jint, jintArray, jbyteArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_ReadOneTemplate
 * Signature: (II[B)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1ReadOneTemplate
  (JNIEnv *, jobject, jint, jint, jbyteArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_ScanTemplate
 * Signature: ([B[I[I)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1ScanTemplate
  (JNIEnv *, jobject, jbyteArray, jintArray, jintArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_FixProvisionalTemplate
 * Signature: ()Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1FixProvisionalTemplate
  (JNIEnv *, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_SetAuthType
 * Signature: (ILcom/supremainc/sfm_sdk/enumeration/UF_AUTH_TYPE;)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1SetAuthType
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_GetAuthType
 * Signature: (I[Lcom/supremainc/sfm_sdk/enumeration/UF_AUTH_TYPE;)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1GetAuthType
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_GetUserIDByAuthType
 * Signature: (Lcom/supremainc/sfm_sdk/enumeration/UF_AUTH_TYPE;[I[I)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1GetUserIDByAuthType
  (JNIEnv *, jobject, jobject, jintArray, jintArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_ResetAllAuthType
 * Signature: ()Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1ResetAllAuthType
  (JNIEnv *, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_AddBlacklist
 * Signature: (I[I)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1AddBlacklist
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_DeleteBlacklist
 * Signature: (I[I)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1DeleteBlacklist
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_GetBlacklist
 * Signature: ([I[I)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1GetBlacklist
  (JNIEnv *, jobject, jintArray, jintArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_DeleteAllBlacklist
 * Signature: ()Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1DeleteAllBlacklist
  (JNIEnv *, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_SetEntranceLimit
 * Signature: (II)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1SetEntranceLimit
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_GetEntranceLimit
 * Signature: (I[I[I)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1GetEntranceLimit
  (JNIEnv *, jobject, jint, jintArray, jintArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_ClearAllEntranceLimit
 * Signature: ()Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1ClearAllEntranceLimit
  (JNIEnv *, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_SaveImage
 * Signature: (Ljava/lang/String;Lcom/supremainc/sfm_sdk/structure/UFImage;)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1SaveImage
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_LoadImage
 * Signature: (Ljava/lang/String;Lcom/supremainc/sfm_sdk/structure/UFImage;)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1LoadImage
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_ReadImage
 * Signature: (Lcom/supremainc/sfm_sdk/structure/UFImage;)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1ReadImage
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_ScanImage
 * Signature: (Lcom/supremainc/sfm_sdk/structure/UFImage;)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1ScanImage
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_Identify
 * Signature: ([I[B)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1Identify
  (JNIEnv *, jobject, jintArray, jbyteArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_IdentifyTemplate
 * Signature: (I[B[I[B)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1IdentifyTemplate
  (JNIEnv *, jobject, jint, jbyteArray, jintArray, jbyteArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_IdentifyImage
 * Signature: (I[B[I[B)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1IdentifyImage
  (JNIEnv *, jobject, jint, jbyteArray, jintArray, jbyteArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_Verify
 * Signature: (I[B)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1Verify
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_VerifyTemplate
 * Signature: (I[BI[B)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1VerifyTemplate
  (JNIEnv *, jobject, jint, jbyteArray, jint, jbyteArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_VerifyHostTemplate
 * Signature: (II[B)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1VerifyHostTemplate
  (JNIEnv *, jobject, jint, jint, jbyteArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_VerifyImage
 * Signature: (I[BI[B)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1VerifyImage
  (JNIEnv *, jobject, jint, jbyteArray, jint, jbyteArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_Enroll
 * Signature: (ILcom/supremainc/sfm_sdk/enumeration/UF_ENROLL_OPTION;[I[I)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1Enroll
  (JNIEnv *, jobject, jint, jobject, jintArray, jintArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_EnrollContinue
 * Signature: (I[I[I)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1EnrollContinue
  (JNIEnv *, jobject, jint, jintArray, jintArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_EnrollAfterVerification
 * Signature: (ILcom/supremainc/sfm_sdk/enumeration/UF_ENROLL_OPTION;[I[I)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1EnrollAfterVerification
  (JNIEnv *, jobject, jint, jobject, jintArray, jintArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_EnrollTemplate
 * Signature: (ILcom/supremainc/sfm_sdk/enumeration/UF_ENROLL_OPTION;I[B[I)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1EnrollTemplate
  (JNIEnv *, jobject, jint, jobject, jint, jbyteArray, jintArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_EnrollMultipleTemplates
 * Signature: (ILcom/supremainc/sfm_sdk/enumeration/UF_ENROLL_OPTION;II[B[I)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1EnrollMultipleTemplates
  (JNIEnv *, jobject, jint, jobject, jint, jint, jbyteArray, jintArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_EnrollMultipleTemplatesEx
 * Signature: (ILcom/supremainc/sfm_sdk/enumeration/UF_ENROLL_OPTION;III[B[I)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1EnrollMultipleTemplatesEx
  (JNIEnv *, jobject, jint, jobject, jint, jint, jint, jbyteArray, jintArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_EnrollImage
 * Signature: (ILcom/supremainc/sfm_sdk/enumeration/UF_ENROLL_OPTION;I[B[I[I)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1EnrollImage
  (JNIEnv *, jobject, jint, jobject, jint, jbyteArray, jintArray, jintArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_Delete
 * Signature: (I)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1Delete
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_DeleteOneTemplate
 * Signature: (II)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1DeleteOneTemplate
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_DeleteMultipleTemplates
 * Signature: (II[I)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1DeleteMultipleTemplates
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_DeleteAll
 * Signature: ()Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1DeleteAll
  (JNIEnv *, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_DeleteAllAfterVerification
 * Signature: ()Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1DeleteAllAfterVerification
  (JNIEnv *, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_Upgrade
 * Signature: (Ljava/lang/String;I)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1Upgrade
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_FormatUserDatabase
 * Signature: ()Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1FormatUserDatabase
  (JNIEnv *, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_ResetSystemConfiguration
 * Signature: ()Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1ResetSystemConfiguration
  (JNIEnv *, jobject);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_WSQ_Decode
 * Signature: ([B[I[I[I[I[I[BI)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1WSQ_1Decode
  (JNIEnv *, jobject, jbyteArray, jintArray, jintArray, jintArray, jintArray, jintArray, jbyteArray, jint);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_ReadImageEx
 * Signature: (Lcom/supremainc/sfm_sdk/structure/UFImage;Lcom/supremainc/sfm_sdk/enumeration/UF_IMAGE_TYPE;I)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1ReadImageEx
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     com_supremainc_sfm_sdk_SFM_SDK_ANDROID
 * Method:    UF_ScanImageEx
 * Signature: (Lcom/supremainc/sfm_sdk/structure/UFImage;Lcom/supremainc/sfm_sdk/enumeration/UF_IMAGE_TYPE;I)Lcom/supremainc/sfm_sdk/enumeration/UF_RET_CODE;
 */
JNIEXPORT jobject JNICALL Java_com_supremainc_sfm_1sdk_SFM_1SDK_1ANDROID_UF_1ScanImageEx
  (JNIEnv *, jobject, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
