/*
 * Copyright (c) 2001 - 2019. Suprema Inc. All rights reserved.
 * Licensed under the MIT license. See LICENSE file in the project root for details.
 */

package com.supremainc.sfm_sdk.not_implemented;

public enum UF_OUTPUT_EVENT {
    UF_OUTPUT_CLEAR_ALL_EVENTS(0x00),
    UF_OUTPUT_ENROLL_WAIT_WIEGAND(0x13),
    UF_OUTPUT_ENROLL_WAIT_FINGER(0x14),
    UF_OUTPUT_ENROLL_PROCESSING(0x15),
    UF_OUTPUT_ENROLL_BAD_FINGER(0x16),
    UF_OUTPUT_ENROLL_SUCCESS(0x17),
    UF_OUTPUT_ENROLL_FAIL(0x18),
    UF_OUTPUT_VERIFY_WAIT_WIEGAND(0x23),
    UF_OUTPUT_VERIFY_WAIT_FINGER(0x24),
    UF_OUTPUT_VERIFY_PROCESSING(0x25),
    UF_OUTPUT_VERIFY_BAD_FINGER(0x26),
    UF_OUTPUT_VERIFY_SUCCESS(0x27),
    UF_OUTPUT_VERIFY_FAIL(0x28),
    UF_OUTPUT_IDENTIFY_WAIT_FINGER(0x34),
    UF_OUTPUT_IDENTIFY_PROCESSING(0x35),
    UF_OUTPUT_IDENTIFY_BAD_FINGER(0x36),
    UF_OUTPUT_IDENTIFY_SUCCESS(0x37),
    UF_OUTPUT_IDENTIFY_FAIL(0x38),
    UF_OUTPUT_DELETE_WAIT_WIEGAND(0x43),
    UF_OUTPUT_DELETE_WAIT_FINGER(0x44),
    UF_OUTPUT_DELETE_PROCESSING(0x45),
    UF_OUTPUT_DELETE_BAD_FINGER(0x46),
    UF_OUTPUT_DELETE_SUCCESS(0x47),
    UF_OUTPUT_DELETE_FAIL(0x48),
    UF_OUTPUT_DETECT_INPUT0(0x54),
    UF_OUTPUT_DETECT_INPUT1(0x55),
    UF_OUTPUT_DETECT_INPUT2(0x56),
    UF_OUTPUT_DETECT_WIEGAND(0x57),
    UF_OUTPUT_DETECT_FINGER(0x58),
    UF_OUTPUT_END_PROCESSING(0x59),
    UF_OUTPUT_VERIFY_DURESS(0x62),
    UF_OUTPUT_IDENTIFY_DURESS(0x63),
    UF_OUTPUT_TAMPER_SWITCH_ON(0x64),
    UF_OUTPUT_TAMPER_SWITCH_OFF(0x65),
    UF_OUTPUT_SYS_STARTED(0x6a),
    UF_OUTPUT_WATCHDOG(0x6b),
    UF_OUTPUT_THREAD_FAIL(0x6c),
    UF_OUTPUT_IDENTIFY_NOT_GRANTED(0x6d),
    UF_OUTPUT_VERIFY_NOT_GRANTED(0x6e),
    UF_OUTPUT_DETECT_SMARTCARD(0x70),
    UF_OUTPUT_BAD_SMARTCARD(0x71),
    UF_OUTPUT_WAIT_SMARTCARD(0x7a),

    ;
    private int value;

    UF_OUTPUT_EVENT(int i) {
        this.value = i;
    }

    public int getValue() {
        return this.value;
    }
}
