/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_supremainc_sfm_sdk_android_MainActivity */

#ifndef _Included_com_supremainc_sfm_sdk_android_MainActivity
#define _Included_com_supremainc_sfm_sdk_android_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
